set script_dir [file dirname [file normalize [info script]]]

set ::env(DESIGN_NAME) el2_n5_soc_wrapper
set ::env(FP_SIZING) absolute
set ::env(DIE_AREA) "0 0 1300 1500"
#set ::env(DIE_AREA) "0 0 1200 1400"

set ::env(GLB_RT_OBS) "met5 $::env(DIE_AREA)"

set ::env(CLOCK_PORT) "HCLK"

set ::env(CLOCK_PERIOD) "10"

set ::env(ROUTING_CORES) 12

set ::env(PL_OPENPHYSYN_OPTIMIZATIONS) 0

set ::env(PL_TARGET_DENSITY) 0.3
set ::env(CELL_PAD) 0

set ::env(DESIGN_IS_CORE) 0
set ::env(SYNTH_READ_BLACKBOX_LIB) 1

set ::env(VERILOG_FILES) "\
   $script_dir/../../verilog/rtl/el2_n5_soc_wrapper.v
   $script_dir/../../verilog/rtl/el2.v"
    
set ::env(GLB_RT_MAXLAYER) 5
set ::env(GLB_RT_ADJUSTMENT) 0.35

set ::env(PDN_CFG) $script_dir/pdn.tcl
 	
set ::env(DIODE_INSERTION_STRATEGY) "4"

set ::env(CLOCK_NET) "\
HCLK
el2.swerv.Gen_AXI_To_AHB_dma_ahb_to_axi4.ahb_addr_cgc.l1clk
el2.swerv.Gen_AXI_To_AHB_dma_ahb_to_axi4.buf_read_error_ff.clk
el2.swerv.Gen_AXI_To_AHB_dma_ahb_to_axi4.cmdbuf_addrff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_dma_ahb_to_axi4.cmdbuf_wdataff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_ifu_axi4_to_ahb.ahbm_data_cgc.l1clk
el2.swerv.Gen_AXI_To_AHB_ifu_axi4_to_ahb.buf_addrff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_ifu_axi4_to_ahb.buf_alignedff.clk
el2.swerv.Gen_AXI_To_AHB_ifu_axi4_to_ahb.buf_dataff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_ifu_axi4_to_ahb.buf_cmd_doneff.clk
el2.swerv.Gen_AXI_To_AHB_lsu_axi4_to_ahb.ahbm_data_cgc.l1clk
el2.swerv.Gen_AXI_To_AHB_lsu_axi4_to_ahb.buf_addrff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_lsu_axi4_to_ahb.buf_alignedff.clk
el2.swerv.Gen_AXI_To_AHB_lsu_axi4_to_ahb.buf_dataff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_lsu_axi4_to_ahb.buf_cmd_byte_ptrff.clk
el2.swerv.Gen_AXI_To_AHB_lsu_axi4_to_ahb.wrbuf_addrff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_lsu_axi4_to_ahb.wrbuf_dataff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_sb_axi4_to_ahb.ahbm_data_cgc.l1clk
el2.swerv.Gen_AXI_To_AHB_sb_axi4_to_ahb.buf_addrff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_sb_axi4_to_ahb.buf_alignedff.clk
el2.swerv.Gen_AXI_To_AHB_sb_axi4_to_ahb.buf_dataff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_sb_axi4_to_ahb.buf_cmd_byte_ptrff.clk
el2.swerv.Gen_AXI_To_AHB_sb_axi4_to_ahb.wrbuf_addrff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_sb_axi4_to_ahb.wrbuf_dataff.genblock_clkhdr.l1clk
el2.swerv.active_cg1.l1clk
el2.swerv.active_cg1.clk
el2.swerv.dbg.dbg_data0_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.dbg_data1_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.dbg_abstractauto_reg.clk
el2.swerv.dbg.dbg_sbaddress0_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.dbg_sbdata0_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.dbg_sbdata1_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.dmcommand_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.dmcommand_regno_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.dmi_rddata_reg.genblock_clkhdr.l1clk
el2.swerv.dbg.sb_free_cgc.l1clk
el2.swerv.dec.arf.gpr_10__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_11__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_12__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_13__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_14__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_15__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_16__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_17__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_18__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_19__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_1__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_20__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_21__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_22__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_23__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_24__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_25__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_26__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_27__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_28__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_29__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_2__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_30__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_31__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_3__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_4__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_5__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_6__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_7__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_8__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.arf.gpr_9__gprff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.cam_array_0__cam_ff.clkhdr.l1clk
el2.swerv.dec.decode.cam_array_1__cam_ff.clkhdr.l1clk
el2.swerv.dec.decode.cam_array_2__cam_ff.clkhdr.l1clk
el2.swerv.dec.decode.cam_array_3__cam_ff.clkhdr.l1clk
el2.swerv.dec.decode.csr_rddata_x_ff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.e1brpcff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.e1ff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.decode.e1ff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.i0_pc_r_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.decode.i0_pc_r_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.i0_result_r_ff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.i0rdff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.illegal_any_ff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.misc1ff.clkhdr.l1clk
el2.swerv.dec.decode.misc2ff.clkhdr.l1clk
el2.swerv.dec.decode.r_d_ff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.decode.r_d_ff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.trap_r_ff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.decode.trap_r_ff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.trap_xff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.decode.trap_xff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.wbff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.decode.write_csr_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.csr_wr_clk
el2.swerv.dec.tlu.dcsr_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.dicad0_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.dicad0h_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.dicawics_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.dpc_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.e4e5_cgc.l1clk
el2.swerv.dec.tlu.e4e5_int_cgc.l1clk
el2.swerv.dec.tlu.excinfo_wb_ff.clkhdr.l1clk
el2.swerv.dec.tlu.exthaltff.clkhdr.l1clk
el2.swerv.dec.tlu.flush_lower_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.flush_lower_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.forcehaltctr_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.freeff.clkhdr.l1clk
el2.swerv.dec.tlu.genblk4_dicad1_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.genblk7_mstatus_ff.clkhdr.l1clk
el2.swerv.dec.tlu.halt_ff.clkhdr.l1clk
el2.swerv.dec.tlu.int_timers.mitb0_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.int_timers.mitb1_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.int_timers.mitcnt0_ffa.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.int_timers.mitcnt0_ffb.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.int_timers.mitcnt1_ffa.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.int_timers.mitcnt1_ffb.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mcause_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mcgc_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mcycleh_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mcyclel_aff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mcyclel_bff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mdccmect_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mdseac_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.meihap_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.meivt_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mepc_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mfdc_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc3_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc3h_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc4_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc4h_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc5_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc5h_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc6_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpmc6h_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpme3_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpme4_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpme5_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mhpme6_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.miccmect_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.micect_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.minstreth_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.minstretl_aff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.minstretl_bff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mpvhalt_ff.clkhdr.l1clk
el2.swerv.dec.tlu.mrac_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mscratch_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata1_t0_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata1_t1_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata1_t2_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata1_t3_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata2_t0_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata2_t1_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata2_t2_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtdata2_t3_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtval_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.mtvec_ff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.npwbc_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.npwbc_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.pwbc_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.dec.tlu.pwbc_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_0__fifo_addr_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_0__fifo_data_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_1__fifo_addr_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_1__fifo_data_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_2__fifo_addr_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_2__fifo_data_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_3__fifo_addr_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_3__fifo_data_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_4__fifo_addr_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_4__fifo_data_dff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.GenFifo_0__fifo_byteen_dff.clk
el2.swerv.dma_ctrl.dbg_dma_bubble_ff.clk
el2.swerv.dma_ctrl.GenFifo_0__fifo_done_bus_dff.clk
el2.swerv.dma_ctrl.rdbuf_addrff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.wrbuf_addrff.genblock_clkhdr.l1clk
el2.swerv.dma_ctrl.wrbuf_dataff.genblock_clkhdr.l1clk
el2.swerv.exu.i_alu.i_pc_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.exu.i_alu.i_pc_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.exu.i_alu.i_result_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_csr_rs1_x_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_div.genblk5_i_new_4bit_div_fullshortq.i_a_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_div.genblk5_i_new_4bit_div_fullshortq.i_b_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_div.genblk5_i_new_4bit_div_fullshortq.i_misc_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_div.genblk5_i_new_4bit_div_fullshortq.i_q_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_div.genblk5_i_new_4bit_div_fullshortq.i_r_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_flush_path_x_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.exu.i_flush_path_x_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.exu.i_flush_r_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.exu.i_flush_r_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.exu.i_misc_ff.clkhdr.l1clk
el2.swerv.exu.i_mul.i_a_x_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_mul.i_b_x_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_npc_r_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.exu.i_npc_r_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.exu.i_predictpacket_x_ff.dff_left.genblock_clkhdr.l1clk
el2.swerv.exu.i_predpipe_r_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_predpipe_x_ff.genblock_clkhdr.l1clk
el2.swerv.exu.i_r_ff0.dff_left.genblock_clkhdr.l1clk
el2.swerv.exu.i_x_ff.genblock_clkhdr.l1clk
el2.swerv.Gen_AXI_To_AHB_ifu_axi4_to_ahb.force_halt_busff.clk
el2.swerv.Gen_AXI_To_AHB_dma_ahb_to_axi4.ahb_addr_cgc.clk
el2.swerv.ifu.aln.bundle2ff.clkhdr.l1clk
el2.swerv.ifu.aln.genblk1_brdata0ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.genblk1_brdata1ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.genblk1_brdata2ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.genblk1_misc0ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.genblk1_misc1ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.genblk1_misc2ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.q0ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.q0pcff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.q1ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.q1pcff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.q2ff.genblock_clkhdr.l1clk
el2.swerv.ifu.aln.q2pcff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.BANKS_0__BHT_CLK_GROUP_0__BHT_FLOPS_0__bht_bank.clk
el2.swerv.ifu.bpred_bp.BANKS_1__BHT_CLK_GROUP_0__BHT_FLOPS_0__bht_bank.clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_0__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_1__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_2__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_3__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_4__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_5__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_6__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_BTB_FAFLOPS_7__btb_fa.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fa_btb_usedf.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.faddrf_ff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.faddrf_ff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.fetchghr.clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_0__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_1__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_2__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_3__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_4__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_5__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_6__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.bpred_bp.retstack_7__rets_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.ifc.faddrf1_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.ifu.ifc.faddrf1_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.ifu.ifc.fbwrite_ff.clkhdr.l1clk
el2.swerv.ifu.mem_ctl.bus_clk.l1clk
el2.swerv.ifu.mem_ctl.bus_clk_f.l1clk
el2.swerv.ifu.mem_ctl.bus_clk_reset.l1clk
el2.swerv.ifu.mem_ctl.fetch_bf_f_c1_cgc.l1clk
el2.swerv.ifu.mem_ctl.ifu_fetch_addr_f_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.ifu_fetch_addr_f_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.ifu_pmu_sigs_ff.clkhdr.l1clk
el2.swerv.ifu.mem_ctl.imb_f_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.imb_f_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.imb_f_scnd_ff.dff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.imb_f_scnd_ff.dff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.misc1_ff.clkhdr.l1clk
el2.swerv.ifu.mem_ctl.misc_ff.clkhdr.l1clk
el2.swerv.ifu.mem_ctl.miss_f_ff.dff_extra.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.miss_f_ff.dff_left.dff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_0__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_0__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_1__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_1__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_2__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_2__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_3__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_3__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_4__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_4__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_5__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_5__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_6__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_6__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_7__byp_data_0_ff.genblock_clkhdr.l1clk
el2.swerv.ifu.mem_ctl.wr_flop_7__byp_data_1_ff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_0__buf_addrff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_0__buf_dataff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_1__buf_addrff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_1__buf_dataff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_2__buf_addrff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_2__buf_dataff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_3__buf_addrff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_3__buf_dataff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.ibuf_addrff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.ibuf_dataff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.obuf_addrff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.obuf_dataff.genblock_clkhdr.l1clk
el2.swerv.lsu.bus_intf.bus_buffer.genblk10_0__buf_ageff.clk
el2.swerv.lsu.bus_intf.bus_buffer.ibuf_byteenff.clk
el2.swerv.lsu.bus_intf.bus_buffer.lsu_bus_obuf_c1_clk
el2.swerv.lsu.bus_intf.bus_buffer.lsu_busm_clk
el2.swerv.lsu.clkdomain.lsu_c1_m_clk
el2.swerv.lsu.bus_intf.is_sideeffects_rff.clk
el2.swerv.lsu.clkdomain.lsu_c2_m_clk
el2.swerv.lsu.bus_intf.bus_buffer.lsu_WrPtr0_rff.clk
el2.swerv.lsu.bus_intf.bus_buffer.ibuf_valid_ff.clk
el2.swerv.lsu.clkdomain.lsu_store_c1_m_clk
el2.swerv.lsu.clkdomain.lsu_store_c1_r_clk
el2.swerv.lsu.dccm_ctl.L2U1_Plus1_0_store_data_hi_rff.genblock_clkhdr.l1clk
el2.swerv.lsu.dccm_ctl.L2U_Plus1_0_lsu_ld_data_corr_rff.genblock_clkhdr.l1clk
el2.swerv.lsu.lsu_lsc_ctl.L2U_Plus1_0_lsu_error_pkt_rff.genblock_clkhdr.l1clk
el2.swerv.lsu.lsu_lsc_ctl.bus_read_data_r_ff.genblock_clkhdr.l1clk
el2.swerv.lsu.lsu_lsc_ctl.end_addr_hi_mff.genblock_clkhdr.l1clk
el2.swerv.lsu.lsu_lsc_ctl.end_addr_hi_rff.genblock_clkhdr.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_0__CLK_GRPS_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_1__CLK_GRPS_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_2__CLK_GRPS_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_3__CLK_GRPS_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_4__CLK_GRPS_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_5__CLK_GRPS_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_6__CLK_GRPS_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.IO_CLK_GRP_7__LAST_GRP_intenable_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.SETREG_10__NON_ZERO_INT_gw_config_ff.clk
el2.swerv.pic_ctrl_inst.pic_addr_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.pic_data_c1_cgc.l1clk
el2.swerv.pic_ctrl_inst.SETREG_10__NON_ZERO_INT_intenable_ff.clk
el2.swerv.pic_ctrl_inst.SETREG_10__NON_ZERO_INT_intpriority_ff.clk
"